#ifndef DEF_VIDEO_H
#define DEF_VIDEO_H

#include "video/utilidades_graficas_sdl/utilidades_graficas_sdl.h"
#include "video/proceso_superficie/proceso_superficie.h"
#include "video/proceso_superficie/proceso_superficie_fundido.h"
#include "video/proceso_superficie/proceso_superficie_base_por_pixel.h"
#include "video/proceso_superficie/proceso_superficie_blanco_negro.h"
#include "video/proceso_superficie/proceso_superficie_cambiar_colores.h"
#include "video/proceso_superficie/proceso_superficie_alterar_canales_rgb.h"
#include "video/camara/camara.h"
#include "video/log_grafico/log_grafico.h"
#include "video/log_grafico/log_grafico_enlazado.h"
#include "video/gestor_color/gestor_color.h"
#include "video/gestor_recursos_graficos/gestor_recursos_graficos.h"
#include "video/pantalla/pantalla.h"
#include "video/recurso_grafico/recurso_grafico.h"
#include "video/recurso_grafico/imagen.h"
#include "video/recurso_grafico/lienzo.h"
#include "video/mapa_colision_bitmap/mapa_colision_bitmap.h"
#include "video/representacion/representacion.h"
#include "video/representacion/representacion_agrupada/representacion_agrupada.h"
#include "video/representacion/representacion_grafica/representacion_grafica.h"
#include "video/representacion/representacion_grafica/representacion_manual.h"
#include "video/representacion/representacion_grafica/representacion_lienzo.h"
#include "video/representacion/representacion_grafica/representacion_compuesta/representacion_compuesta.h"
#include "video/representacion/representacion_grafica/representacion_bitmap/representacion_bitmap.h"
#include "video/representacion/representacion_grafica/representacion_texto/representacion_texto.h"
#include "video/representacion/representacion_grafica/representacion_texto/representacion_texto_fija.h"
#include "video/representacion/representacion_grafica/representacion_texto/representacion_texto_auto.h"
#include "video/representacion/representacion_grafica/representacion_pixeles/representacion_pixeles.h"
#include "video/representacion/primitiva_grafica/primitiva_grafica.h"
#include "video/representacion/primitiva_grafica/primitiva_grafica_linea/primitiva_grafica_linea.h"
#include "video/representacion/primitiva_grafica/primitiva_grafica_circunferencia/primitiva_grafica_circunferencia.h"
#include "video/representacion/primitiva_grafica/representacion_patron/representacion_patron.h"
#include "video/representacion/primitiva_grafica/primitiva_grafica_caja/primitiva_grafica_caja.h"

#endif
